### ISSUE TITLE
Installation issue (HOOBS)

### ISSUE THREAD

**Issue by lhttony** [Sunoo/homebridge-philips-air#11]
Hello, I'm hitting below error when I follow the 3rd step :
to install the CoAPthon :

hoobs@hoobs:/var/lib/homebridge $ sudo pip3 install -U git+https://github.com/Tanganelli/CoAPthon3@89d5173
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/Tanganelli/CoAPthon3@89d5173
  Cloning https://github.com/Tanganelli/CoAPthon3 (to revision 89d5173) to /tmp/pip-req-build-4b2o1erg
  Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/Tanganelli/CoAPthon3 /tmp/pip-req-build-4b2o1erg
Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by Sunoo** [comment]
If you do `sudo apt install git` before the other commands, does that resolve this issue? If so I‘ll update my installation instructions, and if not I’ll continue to help troubleshoot.

**Comment by lhttony** [comment]
Hello, thanks a lot, it passed the 3rd step, but I faced another issue when I install the plugin :

The first try was having access issue :
hoobs@hoobs:/var/lib/homebridge $ npm install -g homebridge-philips-air --unsafe-perm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules


So I've done it again with sudo, but meet below errors :

hoobs@hoobs:/var/lib/homebridge $ sudo npm install -g homebridge-philips-air --unsafe-perm

> node-calls-python@1.4.0 install /usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
  CXX(target) Release/obj.target/nodecallspython/src/addon.o
../src/addon.cpp: In function ‘napi_value__* nodecallspython::createHandler(napi_env, nodecallspython::PyInterpreter*, const string&)’:
../src/addon.cpp:87:19: error: ‘napi_add_finalizer’ was not declared in this scope
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro ‘CHECKNULL’
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
../src/addon.cpp:87:19: note: suggested alternative: ‘napi_finalize’
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro ‘CHECKNULL’
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
make: *** [nodecallspython.target.mk:100: Release/obj.target/nodecallspython/src/addon.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.58-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-calls-python@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-18T10_08_14_647Z-debug.log

**Comment by Sunoo** [comment]
Well, that’s some progress at least. I’ve never used HOOBS, so I’m not sure what’s different about that image. I’ll try to find some time to get it set up soon, and see if I can recreate this issue.

**Comment by Sunoo** [comment]
Can you run `nodejs -v` when you have a chance and let me know what you get? It looks like it is having trouble with the Node API.

**Comment by pawelkami** [comment]
I have the same problem on Raspberry Pi B+ with Raspbian Buster. The problem is when installing `node-calls-python`. I tried also to install older versions of `node-calls-python` package and it also failed. I updated npm and I have python 3.7. I'd like to install this update because I have air purifier which uses CoAP protocol. :)

**Comment by Sunoo** [comment]
@pawelkami Can you also run `nodejs -v` and let me know what you get?

I developed this on a Pi running Buster, so it should run fine on that configuration. I wonder if it’s a conflict with some version of NodeJS or something.

**Comment by pawelkami** [comment]
```bash
$ nodejs -v
v10.21.0
```
I'm wondering if it isn't something related with that my Raspberry Pi is quite old. It has old ARM CPU and maybe some dependencies are not compiled for it.

```bash
$ uname -a
Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
```

**Comment by Sunoo** [comment]
@pawelkami I only tested on NodeJS 12. I’ll try to find some time to install 10 on something soon to see if I can recreate the error there.

**Comment by Sunoo** [comment]
Could one of you possibly upload the debug log that gets generated after the failed compile? The filename should be at the bottom of the output after a failed install.

**Comment by pawelkami** [comment]
```
$ sudo npm install -g homebridge-philips-air --unsafe-perm
> node-calls-python@1.4.0 install /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
> node-gyp rebuild

make: Entering directory '/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
  CXX(target) Release/obj.target/nodecallspython/src/addon.o
../src/addon.cpp: In function 'napi_value__* nodecallspython::createHandler(napi_env, nodecallspython::PyInterpreter*, const string&)':
../src/addon.cpp:87:19: error: 'napi_add_finalizer' was not declared in this scope
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro 'CHECKNULL'
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
../src/addon.cpp:87:19: note: suggested alternative: 'napi_finalize'
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro 'CHECKNULL'
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
../src/addon.cpp: In constructor 'nodecallspython::Python::Python(napi_env)':
../src/addon.cpp:363:25: error: 'make_unique' is not a member of 'std'
             m_py = std::make_unique<PyInterpreter>();
                         ^~~~~~~~~~~
../src/addon.cpp:363:25: note: 'std::make_unique' is defined in header '<memory>'; did you forget to '#include <memory>'?
../src/addon.cpp:10:1:
+#include <memory>

../src/addon.cpp:363:25:
             m_py = std::make_unique<PyInterpreter>();
                         ^~~~~~~~~~~
../src/addon.cpp:363:50: error: expected primary-expression before '>' token
             m_py = std::make_unique<PyInterpreter>();
                                                  ^
../src/addon.cpp:363:52: error: expected primary-expression before ')' token
             m_py = std::make_unique<PyInterpreter>();
                                                    ^
../src/addon.cpp: At global scope:
../src/addon.cpp:565:18: error: ISO C++ forbids declaration of 'NAPI_MODULE_INIT' with no type [-fpermissive]
 NAPI_MODULE_INIT()
                  ^
../src/addon.cpp: In function 'int NAPI_MODULE_INIT()':
../src/addon.cpp:567:42: error: 'env' was not declared in this scope
     return nodecallspython::Python::Init(env, exports);
                                          ^~~
../src/addon.cpp:567:42: note: suggested alternative: 'ecvt'
     return nodecallspython::Python::Init(env, exports);
                                          ^~~
                                          ecvt
../src/addon.cpp:567:47: error: 'exports' was not declared in this scope
     return nodecallspython::Python::Init(env, exports);
                                               ^~~~~~~
make: *** [nodecallspython.target.mk:100: Release/obj.target/nodecallspython/src/addon.o] Error 1
make: Leaving directory '/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.19.97+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-calls-python@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-20T11_41_25_298Z-debug.log
```


And here is log file:

```
$ cat /root/.npm/_logs/2020-06-20T11_41_25_298Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-philips-air',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@6.14.5
3 info using node@v9.11.1
4 verbose npm-session 0a101a320d09a5df
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-philips-air 7023ms (from cache)
8 silly pacote tag manifest for homebridge-philips-air@latest fetched in 7778ms
9 timing stage:loadCurrentTree Completed in 10030ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 46ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 335ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-philips-air@2.0.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/node-calls-python 3121ms (from cache)
18 silly pacote range manifest for node-calls-python@>=1.4.0 fetched in 3310ms
19 silly resolveWithNewModule node-calls-python@1.4.0 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4042ms
21 timing stage:loadIdealTree Completed in 4603ms
22 silly currentTree lib
23 silly idealTree lib
23 silly idealTree └─┬ homebridge-philips-air@2.0.0
23 silly idealTree   └── node-calls-python@1.4.0
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 424ms
26 silly diffTrees action count 2
27 silly diffTrees add node-calls-python@1.4.0
28 silly diffTrees add homebridge-philips-air@2.0.0
29 silly decomposeActions action count 16
30 silly decomposeActions fetch node-calls-python@1.4.0
31 silly decomposeActions extract node-calls-python@1.4.0
32 silly decomposeActions preinstall node-calls-python@1.4.0
33 silly decomposeActions build node-calls-python@1.4.0
34 silly decomposeActions install node-calls-python@1.4.0
35 silly decomposeActions postinstall node-calls-python@1.4.0
36 silly decomposeActions finalize node-calls-python@1.4.0
37 silly decomposeActions refresh-package-json node-calls-python@1.4.0
38 silly decomposeActions fetch homebridge-philips-air@2.0.0
39 silly decomposeActions extract homebridge-philips-air@2.0.0
40 silly decomposeActions preinstall homebridge-philips-air@2.0.0
41 silly decomposeActions build homebridge-philips-air@2.0.0
42 silly decomposeActions install homebridge-philips-air@2.0.0
43 silly decomposeActions postinstall homebridge-philips-air@2.0.0
44 silly decomposeActions finalize homebridge-philips-air@2.0.0
45 silly decomposeActions refresh-package-json homebridge-philips-air@2.0.0
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
49 verbose lock using /root/.npm/_locks/staging-64689f1deb8f5141.lock for /opt/nodejs/lib/node_modules/.staging
50 silly doParallel extract 2
51 silly extract node-calls-python@1.4.0
52 silly extract homebridge-philips-air@2.0.0
53 silly tarball trying node-calls-python@>=1.4.0 by hash: sha512-wVTKaLmFKcQ9pSTEKdQFdihoeOYmbRHgTTEbOVMZppZA9FwBEwMCwIrYADTjuuUdwgFbj4dCtJLguMgfVNjeeQ==
54 silly tarball trying homebridge-philips-air@latest by hash: sha512-ezq22luWiRx5Av6BlBgXdZt7iwNwaLO5/Qo0BJxo3wnavLLh5cOb91hXkjdl0ZmjboqfSqQQla98vKPt4ZSU1g==
55 silly extract homebridge-philips-air@latest extracted to /opt/nodejs/lib/node_modules/.staging/homebridge-philips-air-944b1266 (3777ms)
56 silly extract node-calls-python@>=1.4.0 extracted to /opt/nodejs/lib/node_modules/.staging/node-calls-python-9734ec44 (6003ms)
57 timing action:extract Completed in 6340ms
58 silly doReverseSerial unbuild 16
59 silly doSerial remove 16
60 silly doSerial move 16
61 silly doSerial finalize 16
62 silly finalize /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
63 silly finalize /opt/nodejs/lib/node_modules/homebridge-philips-air
64 timing action:finalize Completed in 2002ms
65 silly doParallel refresh-package-json 2
66 silly refresh-package-json /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
67 silly refresh-package-json /opt/nodejs/lib/node_modules/homebridge-philips-air
68 timing action:refresh-package-json Completed in 2566ms
69 silly doParallel preinstall 2
70 silly preinstall node-calls-python@1.4.0
71 info lifecycle node-calls-python@1.4.0~preinstall: node-calls-python@1.4.0
72 silly preinstall homebridge-philips-air@2.0.0
73 info lifecycle homebridge-philips-air@2.0.0~preinstall: homebridge-philips-air@2.0.0
74 timing action:preinstall Completed in 184ms
75 silly doSerial build 16
76 silly build node-calls-python@1.4.0
77 info linkStuff node-calls-python@1.4.0
78 silly linkStuff node-calls-python@1.4.0 has /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules as its parent node_modules
79 silly linkStuff node-calls-python@1.4.0 is part of a global install
80 silly linkStuff node-calls-python@1.4.0 is installed into a global node_modules
81 silly build homebridge-philips-air@2.0.0
82 info linkStuff homebridge-philips-air@2.0.0
83 silly linkStuff homebridge-philips-air@2.0.0 has /opt/nodejs/lib/node_modules as its parent node_modules
84 silly linkStuff homebridge-philips-air@2.0.0 is part of a global install
85 silly linkStuff homebridge-philips-air@2.0.0 is installed into a global node_modules
86 silly linkStuff homebridge-philips-air@2.0.0 is installed into the top-level global node_modules
87 timing action:build Completed in 148ms
88 silly doSerial global-link 16
89 silly doParallel update-linked 0
90 silly doSerial install 16
91 silly install node-calls-python@1.4.0
92 info lifecycle node-calls-python@1.4.0~install: node-calls-python@1.4.0
93 verbose lifecycle node-calls-python@1.4.0~install: unsafe-perm in lifecycle true
94 verbose lifecycle node-calls-python@1.4.0~install: PATH: /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/node_modules/.bin:/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/.bin:/opt/nodejs/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
95 verbose lifecycle node-calls-python@1.4.0~install: CWD: /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
96 silly lifecycle node-calls-python@1.4.0~install: Args: [ '-c', 'node-gyp rebuild' ]
97 silly lifecycle node-calls-python@1.4.0~install: Returned: code: 1  signal: null
98 info lifecycle node-calls-python@1.4.0~install: Failed to exec install script
99 timing action:install Completed in 63944ms
100 verbose unlock done using /root/.npm/_locks/staging-64689f1deb8f5141.lock for /opt/nodejs/lib/node_modules/.staging
101 timing stage:rollbackFailedOptional Completed in 1646ms
102 timing stage:runTopLevelLifecycles Completed in 92708ms
103 verbose stack Error: node-calls-python@1.4.0 install: `node-gyp rebuild`
103 verbose stack Exit status 1
103 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
103 verbose stack     at EventEmitter.emit (events.js:180:13)
103 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
103 verbose stack     at ChildProcess.emit (events.js:180:13)
103 verbose stack     at maybeClose (internal/child_process.js:936:16)
103 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
104 verbose pkgid node-calls-python@1.4.0
105 verbose cwd /home/pi
106 verbose Linux 4.19.97+
107 verbose argv "/opt/nodejs/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-philips-air" "--unsafe-perm"
108 verbose node v9.11.1
109 verbose npm  v6.14.5
110 error code ELIFECYCLE
111 error errno 1
112 error node-calls-python@1.4.0 install: `node-gyp rebuild`
112 error Exit status 1
113 error Failed at the node-calls-python@1.4.0 install script.
113 error This is probably not a problem with npm. There is likely additional logging output above.
114 verbose exit [ 1, true ]
```

**Comment by Sunoo** [comment]
Okay, I've just pushed a new version of this that removes node-calls-python, so that should resolve the problems you were seeing. If you have any other issues, please feel free to open another issue and I'll do my best to assist.
