### ISSUE TITLE
Plugin error (HTTP Only)

### ISSUE THREAD

**Issue by Synedrus** [Sunoo/homebridge-philips-air#12]
For an unknown reason, my 2000i air purifier recently disconnected from my 2.4 GHz WiFi band and did not automatically reconnect. I have reconfigured the WiFi settings of my unit and it is now connected with the same fixed IP address as before. I am now getting an issue with the plugin when I attempt to add my unit:

`Running Command: npm install homebridge-philips-air-httponly@latest
[6/21/2020, 6:15:32 PM] [Config] Changes to config.json saved.
[6/21/2020, 6:18:20 PM] [Config] Changes to config.json saved.
[6/21/2020, 6:19:05 PM] [Config] Homebridge restart request received
[6/21/2020, 6:19:05 PM] [Config] UI / Bridge settings have not changed; only restarting Homebridge process
[6/21/2020, 6:19:05 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[6/21/2020, 6:19:05 PM] Got SIGTERM, shutting down Homebridge...
[6/21/2020, 6:19:10 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/21/2020, 6:19:15 PM] [HB Supervisor] Restarting Homebridge...
[6/21/2020, 6:19:15 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/21/2020, 6:19:15 PM] [HB Supervisor] Started Homebridge v1.1.1 with PID: 8471
[6/21/2020, 6:19:16 PM] Loaded config.json with 0 accessories and 2 platforms.
[6/21/2020, 6:19:16 PM] ---
[6/21/2020, 6:19:16 PM] Loaded plugin: homebridge-config-ui-x@4.23.0
[6/21/2020, 6:19:16 PM] Registering platform 'homebridge-config-ui-x.config'
[6/21/2020, 6:19:16 PM] ---
[6/21/2020, 6:19:16 PM] Loaded plugin: homebridge-philips-air-httponly@1.1.11
[6/21/2020, 6:19:16 PM] Registering platform 'homebridge-philips-air-httponly.philipsAir'
[6/21/2020, 6:19:16 PM] ---
[6/21/2020, 6:19:16 PM] Loading 2 platforms...
[6/21/2020, 6:19:16 PM] [Config] Initializing config platform...
[6/21/2020, 6:19:16 PM] [Config] Running in Service Mode
[6/21/2020, 6:19:16 PM] [Philips Air Purifier] Initializing philipsAir platform...
[6/21/2020, 6:19:16 PM] [Philips Air Purifier] Initializing platform accessory Philips Air Purifier 2000i...
[6/21/2020, 6:19:16 PM] TypeError: Cannot read property 'key' of undefined
    at philipsAir.addAccessory (/usr/local/lib/node_modules/homebridge-philips-air-httponly/index.js:383:94)
    at /usr/local/lib/node_modules/homebridge-philips-air-httponly/index.js:40:14
    at Array.forEach (<anonymous>)
    at philipsAir.didFinishLaunching (/usr/local/lib/node_modules/homebridge-philips-air-httponly/index.js:39:25)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:160:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
[6/21/2020, 6:19:16 PM] Got SIGTERM, shutting down Homebridge...`

I've never encountered this issue before. I've attempted to fix the issue by installing the plugin both the Homebridge UI and macOS terminal, and adding my purifier through the plugin UI and config editor. Any help is greatly appreciated!

**Comment by Sunoo** [comment]
I think I understand the problem, give me like an hour and if I’m right I’ll push a fix.

**Comment by Sunoo** [comment]
Forget that "hour" thing. Fix is in and published. If you do an update on the plugin, it should get you working again. Sorry about that.

**Comment by Synedrus** [comment]
You needn't apologise! Thank you for getting on to it so quickly.

**Comment by Sunoo** [comment]
Great, glad that fixed it for you.
