### ISSUE TITLE
Receiving Python Error

### ISSUE THREAD

**Issue by jamesg311** [Sunoo/homebridge-philips-air#72]
See below for the error I'm getting when firing up Homebridge. Can you help?

`[Living Room Air Purifier] Unable to load status info: Error: Command failed: python3 /usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.7.163 --protocol coap --status
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
ModuleNotFoundError: No module named 'pyairctrl'`

`Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
ModuleNotFoundError: No module named 'pyairctrl'`

` [Living Room Air Purifier] Unable to load filter info: Error: Command failed: python3 /usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.7.163 --protocol coap --status
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
ModuleNotFoundError: No module named 'pyairctrl'`

**Comment by jamesg311** [comment]
Pinging for any help on this.

**Comment by jamesg311** [comment]
Resolving. Somehow py-air-ctrl was removed from my installation. Going through setup instructions and running the pip3 install py-air-control command fixed it.
