### ISSUE TITLE
I can't get my fan speed control to work

### ISSUE THREAD

**Issue by swl2861** [Sunoo/homebridge-philips-air#87]
The LED light dim function works but I can't control the speed of my fan. Also I don't get any air quality info.
I have a 2889/10 with Shanghai wifi chip and my Homebridge is running on Windows 10 x64. I had to copy the python.exe to python3.exe to make it work.

When I start homebridge:
[7-11-2020 01:30:01] [Philips Air] [Philips 2889/10] Initializing accessory...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
    self._send_ack(transaction)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
    self.send_datagram(ack)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

[7-11-2020 01:30:29] [Philips Air] [Philips 2889/10] Initializing accessory...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
    self._send_ack(transaction)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
    self.send_datagram(ack)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
[7-11-2020 01:30:29] [SWL-HUB] DidFinishLaunching
[7-11-2020 01:30:29] [SWL-HUB] (SWL-HUB)INFO - Loading activities...
[7-11-2020 01:30:29] [Philips Air] [Philips 2889/10] Unable to load firmware info: TypeError: Cannot read property 'replace' of undefined
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
    self._send_ack(transaction)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
    self.send_datagram(ack)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
    self._send_ack(transaction)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
    self.send_datagram(ack)
  File "C:\Python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

When I try to read status:
C:\Windows\System32>airctrl --ipaddr 192.168.2.8
Exchanging secret key with the device ...
Traceback (most recent call last):
  File "c:\python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\python39\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\python39\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "c:\python39\lib\socket.py", line 843, in create_connection
    raise err
  File "c:\python39\lib\socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\airctrl.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\pyairctrl\airctrl.py", line 444, in main
    c = HTTPAirCli(device["ip"])
  File "c:\python39\lib\site-packages\pyairctrl\airctrl.py", line 100, in __init__
    self._client = HTTPAirClient(host, debug)
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 108, in __init__
    self.load_key()
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 156, in load_key
    self._get_key()
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 119, in _get_key
    with urllib.request.urlopen(req) as response:
  File "c:\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\python39\lib\urllib\request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\python39\lib\urllib\request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

When I try to set protocol CoAP:
C:\Windows\System32>airctrl --ipaddr 192.168.2.8 --protocol coap
Unexpected error:'Thread' object has no attribute 'isAlive'
Exception in thread Thread-1:
Traceback (most recent call last):
File "c:\python39\lib\threading.py", line 950, in _bootstrap_inner
self.run()
File "c:\python39\lib\threading.py", line 888, in run
self._target(*self._args, **self._kwargs)
File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
self._send_ack(transaction)
File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
self.send_datagram(ack)
File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by swl2861** [comment]
I think I've found the issue: akunzai commented on 8 Oct
seems threading.Thread 's method isAlive() was renamed to is_alive() since Python 3.9.0

see micheles/decorator#75

**Comment by swl2861** [comment]
It's working!
